name: Unit Test

on: [push]

jobs:

  haxelib:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        haxelib install mcover > /dev/null
        haxelib install hamcrest > /dev/null
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install hxp > /dev/null
        haxelib run hxp --install-hxp-alias

    - name: Install "openfl" command alias
      run: |
        haxelib run openfl setup -alias -y

    - name: Run unit tests
      run: |
        hxp unit-test neko

  npm:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo apt-get install npm -y

    - name: Install dependencies
      run: |
        npm install -g

    - name: Run unit tests
      run: |
        npm run build -g
        npm run test -g

