name: Unit Tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        haxelib install lime --quiet
        haxelib install utest --quiet
        haxelib install hxp --quiet
        haxelib run hxp --install-hxp-alias
        haxelib run lime setup -alias -y
        lime || alias lime="haxelib run lime"

    - name: Install "openfl" command alias
      run: |
        haxelib run openfl setup -alias -y

    - name: Run unit tests
      run: |
        hxp unit-test neko

    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      if: github.repository == github.event.pull_request.head.repo.full_name
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#00C07F"
        message: "https://github.com/openfl/openfl/actions\nUnit tests succeeded."

    - name: Notify Discord (failure)
      uses: appleboy/discord-action@master
      if: github.repository == github.event.pull_request.head.repo.full_name && failure()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#FF6562"
        message: "https://github.com/openfl/openfl/actions\nUnit tests failed."
