name: Unit Test

on: [push]

jobs:

  haxelib:
    name: "Haxelib"
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        haxelib install mcover > /dev/null
        haxelib install hamcrest > /dev/null
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install hxp > /dev/null
        haxelib run hxp --install-hxp-alias

    - name: Install "openfl" command alias
      run: |
        haxelib run openfl setup -alias -y

    - name: Run unit tests
      run: |
        hxp unit-test neko

    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#00C07F"
        message: "Haxelib unit tests succeeded.\nhttps://github.com/openfl/openfl/actions"
    
    - name: Notify Discord (failure)
      uses: appleboy/discord-action@master
      if: failure()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#FF6562"
        message: "Haxelib unit tests failed.\nhttps://github.com/openfl/openfl/actions"
        
  npm:
    name: "NPM"
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: |
          add-apt-repository ppa:haxe/releases -y
          apt-get update
          apt-get install haxe -y
          mkdir $GITHUB_WORKSPACE/.haxelib
          haxelib setup $GITHUB_WORKSPACE/.haxelib
          haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: npm install
        
    - name: Build openfl.js
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: npm run build

    - name: Run unit tests
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: npm run test
    
    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#00C07F"
        message: "NPM unit tests succeeded.\nhttps://github.com/openfl/openfl/actions"
    
    - name: Notify Discord (failure)
      uses: appleboy/discord-action@master
      if: failure()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#FF6562"
        message: "NPM unit tests failed.\nhttps://github.com/openfl/openfl/actions"

